GRANT_PASSWORD = "password"
GRANT_CLIENT_CREDENTIALS = "client_credentials"
GRANT_REFRESH_TOKEN = "refresh_token"

ALL_GRANTS = [GRANT_PASSWORD, GRANT_CLIENT_CREDENTIALS, GRANT_REFRESH_TOKEN]

SECONDS_PER_DAY = 86400

PBKDF2_DEFAULT_ITERATIONS = 200_000
